// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBackendAPI.Data;

#nullable disable

namespace MyBackendAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505063504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyBackendAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "phone",
                            ImageUrl = "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-pro-max_3.png",
                            Name = "iPhone 15 Pro Max",
                            Price = 34990000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "phone",
                            ImageUrl = "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-s24-ultra.png",
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 31990000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "laptop",
                            ImageUrl = "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook-pro-14-inch-m3-1_2.png",
                            Name = "MacBook Pro M3 14\"",
                            Price = 49990000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "laptop",
                            ImageUrl = "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_14__5_7.png",
                            Name = "Laptop Gaming ASUS ROG",
                            Price = 42990000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "accessory",
                            ImageUrl = "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/g/r/group_169_2.png",
                            Name = "AirPods Pro 2",
                            Price = 5990000m
                        },
                        new
                        {
                            Id = 6,
                            Category = "accessory",
                            ImageUrl = "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/s/o/sony_wh-1000xm5_1.png",
                            Name = "Tai nghe Sony WH-1000XM5",
                            Price = 7490000m
                        },
                        new
                        {
                            Id = 7,
                            Category = "phone",
                            ImageUrl = "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/x/i/xiaomi-14-ultra.png",
                            Name = "Xiaomi 14 Ultra",
                            Price = 23990000m
                        },
                        new
                        {
                            Id = 8,
                            Category = "laptop",
                            ImageUrl = "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_7__7_16.png",
                            Name = "Dell XPS 15",
                            Price = 45990000m
                        },
                        new
                        {
                            Id = 9,
                            Category = "phone",
                            ImageUrl = "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/o/p/oppo-find-x7-ultra_1__1.png",
                            Name = "OPPO Find X7 Ultra",
                            Price = 22990000m
                        },
                        new
                        {
                            Id = 10,
                            Category = "laptop",
                            ImageUrl = "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/h/p/hp-spectre-x360.png",
                            Name = "HP Spectre x360",
                            Price = 38990000m
                        },
                        new
                        {
                            Id = 11,
                            Category = "accessory",
                            ImageUrl = "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/k/e/keychron-k8.png",
                            Name = "Bàn phím cơ Keychron K8",
                            Price = 2490000m
                        },
                        new
                        {
                            Id = 12,
                            Category = "accessory",
                            ImageUrl = "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/m/x/mx-master-3s_2.png",
                            Name = "Chuột Logitech MX Master 3S",
                            Price = 2190000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
